<?php

$baseDir = realpath("<путь до php-api-client>/src");

if (!$baseDir) {
    throw new RuntimeException("Папка src не найдена!");
}

// Перечисление всех файлов в SDK
$files = [
    'AirlineInfoInterface',
    'AmountInterface',
    'ApiCpanelArraySerializeInterface',
    'ApiRequestInterface',
    'AuthorizationInterface',
    'BillingInterface',
    'CaptureInterface',
    'ClientInterface',
    'DeliveryInterface',
    'DestinationInterface',
    'DetailsInterface',
    'CardDetailsInterface',
    'IdentityDocumentInterface',
    'MarketplaceSubmerchantInterface',
    'MerchantInterface',
    'MerchantTokenInterface',
    'OrderDataInterface',
    'PaymentDetailsInterface',
    'PaymentInterface',
    'PaymentPageOptionsInterface',
    'PaymentResultInterface',
    'PayoutDestinationInterface',
    'PayoutInterface',
    'PayoutSourceInterface',
    'ProductInterface',
    'QstInterface',
    'QstToArrayInterface',
    'QstSchemaAddressInterface',
    'QstSchemaBankAccountInterface',
    'QstSchemaCeoInterface',
    'QstSchemaIdentityDocInterface',
    'QstSchemaInterface',
    'QstSchemaOwnerInterface',
    'RefundInterface',
    'StoredCredentialsInterface',
    'TransactionInterface',
    'WebhookAuthorizationInterface',
    'WebhookInterface',
    'WebhookStoredCredentialsInterface',
    'Payout/PayoutCommissionInterface',
    'Payout/PayoutOrderDataInterface',
    'Payout/PayoutPaymentResultInterface',
    'Payout/PayoutRecipientInterface',
    'Payout/PayoutWebhookInterface',
    'ApiRequest',
    'Amount',
    'ApiCpanelUserException',
    'ApiCpanelUserRequest',
    'Authorization',
    'Billing',
    'Capture',
    'CaptureApiRequest',
    'CardDetails',
    'Client',
    'CpanelUser',
    'Delivery',
    'Details',
    'Group',
    'IdentityDocument',
    'MarketplaceSubmerchant',
    'Merchant',
    'MerchantToken',
    'OneTimeUseToken',
    'OrderData',
    'Payment',
    'PaymentException',
    'PaymentMethods',
    'PaymentPageOptions',
    'PaymentReference',
    'PaymentResult',
    'Payout',
    'PayoutDestination',
    'PayoutMobileDestination',
    'PayoutSource',
    'PhoneDetails',
    'PodeliMerchant',
    'PodeliMerchantAddress',
    'PodeliMerchantBankDetails',
    'Privilege',
    'Product',
    'Qst',
    'QstSchema',
    'QstSchemaAddressAbstract',
    'QstSchemaCheckableTrait',
    'QstSchemaActualAddress',
    'QstSchemaBankAccount',
    'QstSchemaCeo',
    'QstSchemaIdentityDoc',
    'QstSchemaLegalAddress',
    'QstSchemaOwner',
    'QstSchemaPostAddress',
    'Refund',
    'Role',
    'SessionRequest',
    'Std',
    'StoredCredentials',
    'SubmerchantReceipt',
    'Webhook',
    'WebhookAuthorization',
    'WebhookStoredCredentials',
    'Widget',
    'Payout/PayoutCommission',
    'Payout/PayoutPaymentResult',
    'Payout/PayoutPayoutOrderData',
    'Payout/PayoutRecipient',
    'Payout/PayoutWebhook'
];

// Подключение файлов к проекту
foreach ($files as $file) {
    require_once $baseDir . "/" . $file . ".php";
}

unset ($files);
unset ($file);